services:
  web:
    image: kubamarchut/makelongurl:latest
    ports:
      - "80:80"
    environment:
      ABUSEIPDB_APIKEY: ${ABUSEIPDB_APIKEY}
    depends_on: 
      - mongoDB
    networks:
      - node-network
  mongoDB:
    image: "mongo"
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'
    networks:
      - node-network

volumes:
  mongodata:

networks:
  node-network:
    driver: bridge