services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - node-network
  mongoDB:
    image: "mongo"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge