services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on: 
      - mongoDB
    networks:
      - node-network
  mongoDB:
    image: "mongo"
    ports:
      - '27017:27017'
    networks:
      - node-network

networks:
  node-network:
    driver: bridge